server:
  port: 8083
  context-path: /Server

#druid多数据源配置
spring:
  datasource:
    druid:
      username: root
      password: Gnkj@12345
      #password: root


      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/truck_counts?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
      url: jdbc:mysql://222.74.94.190:3309/truck_counts1?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8

      initialSize: 5
      minIdle: 5
      maxActive: 20
#Mapper.xml所在的位置
mybatis-plus:
  #mapper-locations: classpath:mybatis/mapper/*.xml
  mapper-locations: classpath:mappers/*.xml
  #扫描的包名
  type-aliases-package: com.gradproject.server.entity
  config-location: classpath:mybatis/mybatis.cfg.xml
  #设置，mapper 接口路径，mapper 接口对应的xml 配置文件
  package:
    path: com.gradproject.server.dao

